// AuditService is the wire contract codeintel-app uses to forward
// audit events to codeintel-backend for durable persistence.
//
// App fires events from the request path (e.g. POST /api/connections
// success → connection.created event). Backend persists each event
// into the Postgres audit table (later) and / or forwards to a
// SIEM. The contract is one-way: app does not wait for backend's
// persistence to ack before returning the HTTP response.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/codeintel/v1/audit_service.proto

package codeintelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActorType discriminates the subject performing an audited action.
type ActorType int32

const (
	ActorType_ACTOR_TYPE_UNSPECIFIED ActorType = 0
	ActorType_ACTOR_TYPE_USER        ActorType = 1
	ActorType_ACTOR_TYPE_API_KEY     ActorType = 2
	ActorType_ACTOR_TYPE_SYSTEM      ActorType = 3
)

// Enum value maps for ActorType.
var (
	ActorType_name = map[int32]string{
		0: "ACTOR_TYPE_UNSPECIFIED",
		1: "ACTOR_TYPE_USER",
		2: "ACTOR_TYPE_API_KEY",
		3: "ACTOR_TYPE_SYSTEM",
	}
	ActorType_value = map[string]int32{
		"ACTOR_TYPE_UNSPECIFIED": 0,
		"ACTOR_TYPE_USER":        1,
		"ACTOR_TYPE_API_KEY":     2,
		"ACTOR_TYPE_SYSTEM":      3,
	}
)

func (x ActorType) Enum() *ActorType {
	p := new(ActorType)
	*p = x
	return p
}

func (x ActorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_codeintel_v1_audit_service_proto_enumTypes[0].Descriptor()
}

func (ActorType) Type() protoreflect.EnumType {
	return &file_proto_codeintel_v1_audit_service_proto_enumTypes[0]
}

func (x ActorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorType.Descriptor instead.
func (ActorType) EnumDescriptor() ([]byte, []int) {
	return file_proto_codeintel_v1_audit_service_proto_rawDescGZIP(), []int{0}
}

// TargetType discriminates the subject being acted upon.
type TargetType int32

const (
	TargetType_TARGET_TYPE_UNSPECIFIED TargetType = 0
	TargetType_TARGET_TYPE_ORG         TargetType = 1
	TargetType_TARGET_TYPE_CONNECTION  TargetType = 2
	TargetType_TARGET_TYPE_SECRET      TargetType = 3
	TargetType_TARGET_TYPE_MODEL       TargetType = 4
)

// Enum value maps for TargetType.
var (
	TargetType_name = map[int32]string{
		0: "TARGET_TYPE_UNSPECIFIED",
		1: "TARGET_TYPE_ORG",
		2: "TARGET_TYPE_CONNECTION",
		3: "TARGET_TYPE_SECRET",
		4: "TARGET_TYPE_MODEL",
	}
	TargetType_value = map[string]int32{
		"TARGET_TYPE_UNSPECIFIED": 0,
		"TARGET_TYPE_ORG":         1,
		"TARGET_TYPE_CONNECTION":  2,
		"TARGET_TYPE_SECRET":      3,
		"TARGET_TYPE_MODEL":       4,
	}
)

func (x TargetType) Enum() *TargetType {
	p := new(TargetType)
	*p = x
	return p
}

func (x TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_codeintel_v1_audit_service_proto_enumTypes[1].Descriptor()
}

func (TargetType) Type() protoreflect.EnumType {
	return &file_proto_codeintel_v1_audit_service_proto_enumTypes[1]
}

func (x TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetType.Descriptor instead.
func (TargetType) EnumDescriptor() ([]byte, []int) {
	return file_proto_codeintel_v1_audit_service_proto_rawDescGZIP(), []int{1}
}

// Event is the structured payload an Emitter sends. Field order
// here pins the proto wire layout; the Go-side audit.Event mirrors
// this shape.
type Event struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Action     string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	ActorId    string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorType  ActorType              `protobuf:"varint,3,opt,name=actor_type,json=actorType,proto3,enum=codeintel.v1.ActorType" json:"actor_type,omitempty"`
	TargetId   string                 `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType TargetType             `protobuf:"varint,5,opt,name=target_type,json=targetType,proto3,enum=codeintel.v1.TargetType" json:"target_type,omitempty"`
	OrgId      int32                  `protobuf:"varint,6,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	RequestId  string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Time       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	// Metadata is a free-form key→value map for event-specific
	// context. Values are JSON-encoded strings so the wire format
	// stays language-agnostic.
	Metadata      map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_codeintel_v1_audit_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codeintel_v1_audit_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_codeintel_v1_audit_service_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Event) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Event) GetActorType() ActorType {
	if x != nil {
		return x.ActorType
	}
	return ActorType_ACTOR_TYPE_UNSPECIFIED
}

func (x *Event) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Event) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *Event) GetOrgId() int32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *Event) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Event) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Event) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRequest) Reset() {
	*x = EmitRequest{}
	mi := &file_proto_codeintel_v1_audit_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRequest) ProtoMessage() {}

func (x *EmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codeintel_v1_audit_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRequest.ProtoReflect.Descriptor instead.
func (*EmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_codeintel_v1_audit_service_proto_rawDescGZIP(), []int{1}
}

func (x *EmitRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type EmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitResponse) Reset() {
	*x = EmitResponse{}
	mi := &file_proto_codeintel_v1_audit_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResponse) ProtoMessage() {}

func (x *EmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codeintel_v1_audit_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResponse.ProtoReflect.Descriptor instead.
func (*EmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_codeintel_v1_audit_service_proto_rawDescGZIP(), []int{2}
}

var File_proto_codeintel_v1_audit_service_proto protoreflect.FileDescriptor

const file_proto_codeintel_v1_audit_service_proto_rawDesc = "" +
	"\n" +
	"&proto/codeintel/v1/audit_service.proto\x12\fcodeintel.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x03\n" +
	"\x05Event\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x126\n" +
	"\n" +
	"actor_type\x18\x03 \x01(\x0e2\x17.codeintel.v1.ActorTypeR\tactorType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x129\n" +
	"\vtarget_type\x18\x05 \x01(\x0e2\x18.codeintel.v1.TargetTypeR\n" +
	"targetType\x12\x15\n" +
	"\x06org_id\x18\x06 \x01(\x05R\x05orgId\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12.\n" +
	"\x04time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12=\n" +
	"\bmetadata\x18\t \x03(\v2!.codeintel.v1.Event.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\vEmitRequest\x12)\n" +
	"\x05event\x18\x01 \x01(\v2\x13.codeintel.v1.EventR\x05event\"\x0e\n" +
	"\fEmitResponse*k\n" +
	"\tActorType\x12\x1a\n" +
	"\x16ACTOR_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fACTOR_TYPE_USER\x10\x01\x12\x16\n" +
	"\x12ACTOR_TYPE_API_KEY\x10\x02\x12\x15\n" +
	"\x11ACTOR_TYPE_SYSTEM\x10\x03*\x89\x01\n" +
	"\n" +
	"TargetType\x12\x1b\n" +
	"\x17TARGET_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTARGET_TYPE_ORG\x10\x01\x12\x1a\n" +
	"\x16TARGET_TYPE_CONNECTION\x10\x02\x12\x16\n" +
	"\x12TARGET_TYPE_SECRET\x10\x03\x12\x15\n" +
	"\x11TARGET_TYPE_MODEL\x10\x042O\n" +
	"\fAuditService\x12?\n" +
	"\x04Emit\x12\x19.codeintel.v1.EmitRequest\x1a\x1a.codeintel.v1.EmitResponse\"\x00B*Z(codeintel/proto/codeintel/v1;codeintelv1b\x06proto3"

var (
	file_proto_codeintel_v1_audit_service_proto_rawDescOnce sync.Once
	file_proto_codeintel_v1_audit_service_proto_rawDescData []byte
)

func file_proto_codeintel_v1_audit_service_proto_rawDescGZIP() []byte {
	file_proto_codeintel_v1_audit_service_proto_rawDescOnce.Do(func() {
		file_proto_codeintel_v1_audit_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_codeintel_v1_audit_service_proto_rawDesc), len(file_proto_codeintel_v1_audit_service_proto_rawDesc)))
	})
	return file_proto_codeintel_v1_audit_service_proto_rawDescData
}

var file_proto_codeintel_v1_audit_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_codeintel_v1_audit_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_codeintel_v1_audit_service_proto_goTypes = []any{
	(ActorType)(0),                // 0: codeintel.v1.ActorType
	(TargetType)(0),               // 1: codeintel.v1.TargetType
	(*Event)(nil),                 // 2: codeintel.v1.Event
	(*EmitRequest)(nil),           // 3: codeintel.v1.EmitRequest
	(*EmitResponse)(nil),          // 4: codeintel.v1.EmitResponse
	nil,                           // 5: codeintel.v1.Event.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_codeintel_v1_audit_service_proto_depIdxs = []int32{
	0, // 0: codeintel.v1.Event.actor_type:type_name -> codeintel.v1.ActorType
	1, // 1: codeintel.v1.Event.target_type:type_name -> codeintel.v1.TargetType
	6, // 2: codeintel.v1.Event.time:type_name -> google.protobuf.Timestamp
	5, // 3: codeintel.v1.Event.metadata:type_name -> codeintel.v1.Event.MetadataEntry
	2, // 4: codeintel.v1.EmitRequest.event:type_name -> codeintel.v1.Event
	3, // 5: codeintel.v1.AuditService.Emit:input_type -> codeintel.v1.EmitRequest
	4, // 6: codeintel.v1.AuditService.Emit:output_type -> codeintel.v1.EmitResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_codeintel_v1_audit_service_proto_init() }
func file_proto_codeintel_v1_audit_service_proto_init() {
	if File_proto_codeintel_v1_audit_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_codeintel_v1_audit_service_proto_rawDesc), len(file_proto_codeintel_v1_audit_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_codeintel_v1_audit_service_proto_goTypes,
		DependencyIndexes: file_proto_codeintel_v1_audit_service_proto_depIdxs,
		EnumInfos:         file_proto_codeintel_v1_audit_service_proto_enumTypes,
		MessageInfos:      file_proto_codeintel_v1_audit_service_proto_msgTypes,
	}.Build()
	File_proto_codeintel_v1_audit_service_proto = out.File
	file_proto_codeintel_v1_audit_service_proto_goTypes = nil
	file_proto_codeintel_v1_audit_service_proto_depIdxs = nil
}
