// IndexExecutorService is the backend-to-indexer execution contract for
// one durable indexing subjob. Backend owns queue claim, heartbeat,
// artifact validation, and persistence; the indexer owns CPU-heavy
// extraction for the assigned layer.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.0
// source: codeintel/v1/index_executor_service.proto

package codeintelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IndexExecutorService_ExecuteSubjob_FullMethodName = "/codeintel.v1.IndexExecutorService/ExecuteSubjob"
)

// IndexExecutorServiceClient is the client API for IndexExecutorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndexExecutorServiceClient interface {
	ExecuteSubjob(ctx context.Context, in *ExecuteIndexSubjobRequest, opts ...grpc.CallOption) (*ExecuteIndexSubjobResponse, error)
}

type indexExecutorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexExecutorServiceClient(cc grpc.ClientConnInterface) IndexExecutorServiceClient {
	return &indexExecutorServiceClient{cc}
}

func (c *indexExecutorServiceClient) ExecuteSubjob(ctx context.Context, in *ExecuteIndexSubjobRequest, opts ...grpc.CallOption) (*ExecuteIndexSubjobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteIndexSubjobResponse)
	err := c.cc.Invoke(ctx, IndexExecutorService_ExecuteSubjob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexExecutorServiceServer is the server API for IndexExecutorService service.
// All implementations must embed UnimplementedIndexExecutorServiceServer
// for forward compatibility.
type IndexExecutorServiceServer interface {
	ExecuteSubjob(context.Context, *ExecuteIndexSubjobRequest) (*ExecuteIndexSubjobResponse, error)
	mustEmbedUnimplementedIndexExecutorServiceServer()
}

// UnimplementedIndexExecutorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexExecutorServiceServer struct{}

func (UnimplementedIndexExecutorServiceServer) ExecuteSubjob(context.Context, *ExecuteIndexSubjobRequest) (*ExecuteIndexSubjobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteSubjob not implemented")
}
func (UnimplementedIndexExecutorServiceServer) mustEmbedUnimplementedIndexExecutorServiceServer() {}
func (UnimplementedIndexExecutorServiceServer) testEmbeddedByValue()                              {}

// UnsafeIndexExecutorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexExecutorServiceServer will
// result in compilation errors.
type UnsafeIndexExecutorServiceServer interface {
	mustEmbedUnimplementedIndexExecutorServiceServer()
}

func RegisterIndexExecutorServiceServer(s grpc.ServiceRegistrar, srv IndexExecutorServiceServer) {
	// If the following call panics, it indicates UnimplementedIndexExecutorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IndexExecutorService_ServiceDesc, srv)
}

func _IndexExecutorService_ExecuteSubjob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteIndexSubjobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexExecutorServiceServer).ExecuteSubjob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexExecutorService_ExecuteSubjob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexExecutorServiceServer).ExecuteSubjob(ctx, req.(*ExecuteIndexSubjobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IndexExecutorService_ServiceDesc is the grpc.ServiceDesc for IndexExecutorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndexExecutorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codeintel.v1.IndexExecutorService",
	HandlerType: (*IndexExecutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteSubjob",
			Handler:    _IndexExecutorService_ExecuteSubjob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "codeintel/v1/index_executor_service.proto",
}
