// IndexPlanService is the typed Rust-indexer-to-Go-backend
// handoff for durable index subjob planning.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.0
// source: codeintel/v1/index_plan_service.proto

package codeintelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IndexPlanService_WritePlan_FullMethodName = "/codeintel.v1.IndexPlanService/WritePlan"
)

// IndexPlanServiceClient is the client API for IndexPlanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndexPlanServiceClient interface {
	WritePlan(ctx context.Context, in *WriteIndexPlanRequest, opts ...grpc.CallOption) (*WriteIndexPlanResponse, error)
}

type indexPlanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexPlanServiceClient(cc grpc.ClientConnInterface) IndexPlanServiceClient {
	return &indexPlanServiceClient{cc}
}

func (c *indexPlanServiceClient) WritePlan(ctx context.Context, in *WriteIndexPlanRequest, opts ...grpc.CallOption) (*WriteIndexPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteIndexPlanResponse)
	err := c.cc.Invoke(ctx, IndexPlanService_WritePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexPlanServiceServer is the server API for IndexPlanService service.
// All implementations must embed UnimplementedIndexPlanServiceServer
// for forward compatibility.
type IndexPlanServiceServer interface {
	WritePlan(context.Context, *WriteIndexPlanRequest) (*WriteIndexPlanResponse, error)
	mustEmbedUnimplementedIndexPlanServiceServer()
}

// UnimplementedIndexPlanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexPlanServiceServer struct{}

func (UnimplementedIndexPlanServiceServer) WritePlan(context.Context, *WriteIndexPlanRequest) (*WriteIndexPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WritePlan not implemented")
}
func (UnimplementedIndexPlanServiceServer) mustEmbedUnimplementedIndexPlanServiceServer() {}
func (UnimplementedIndexPlanServiceServer) testEmbeddedByValue()                          {}

// UnsafeIndexPlanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexPlanServiceServer will
// result in compilation errors.
type UnsafeIndexPlanServiceServer interface {
	mustEmbedUnimplementedIndexPlanServiceServer()
}

func RegisterIndexPlanServiceServer(s grpc.ServiceRegistrar, srv IndexPlanServiceServer) {
	// If the following call panics, it indicates UnimplementedIndexPlanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IndexPlanService_ServiceDesc, srv)
}

func _IndexPlanService_WritePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteIndexPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexPlanServiceServer).WritePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexPlanService_WritePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexPlanServiceServer).WritePlan(ctx, req.(*WriteIndexPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IndexPlanService_ServiceDesc is the grpc.ServiceDesc for IndexPlanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndexPlanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codeintel.v1.IndexPlanService",
	HandlerType: (*IndexPlanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WritePlan",
			Handler:    _IndexPlanService_WritePlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "codeintel/v1/index_plan_service.proto",
}
