// IndexPlanService is the typed Rust-indexer-to-Go-backend
// handoff for durable index subjob planning.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: codeintel/v1/index_plan_service.proto

package codeintelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SCIPProjectPlan struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Language         string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	ProjectRoot      string                 `protobuf:"bytes,2,opt,name=project_root,json=projectRoot,proto3" json:"project_root,omitempty"`
	Indexer          string                 `protobuf:"bytes,3,opt,name=indexer,proto3" json:"indexer,omitempty"`
	ScipWorkerClass  string                 `protobuf:"bytes,4,opt,name=scip_worker_class,json=scipWorkerClass,proto3" json:"scip_worker_class,omitempty"`
	ToolchainDigest  *string                `protobuf:"bytes,5,opt,name=toolchain_digest,json=toolchainDigest,proto3,oneof" json:"toolchain_digest,omitempty"`
	ImageDigest      *string                `protobuf:"bytes,6,opt,name=image_digest,json=imageDigest,proto3,oneof" json:"image_digest,omitempty"`
	ProjectInputHash *string                `protobuf:"bytes,7,opt,name=project_input_hash,json=projectInputHash,proto3,oneof" json:"project_input_hash,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SCIPProjectPlan) Reset() {
	*x = SCIPProjectPlan{}
	mi := &file_codeintel_v1_index_plan_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SCIPProjectPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCIPProjectPlan) ProtoMessage() {}

func (x *SCIPProjectPlan) ProtoReflect() protoreflect.Message {
	mi := &file_codeintel_v1_index_plan_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCIPProjectPlan.ProtoReflect.Descriptor instead.
func (*SCIPProjectPlan) Descriptor() ([]byte, []int) {
	return file_codeintel_v1_index_plan_service_proto_rawDescGZIP(), []int{0}
}

func (x *SCIPProjectPlan) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SCIPProjectPlan) GetProjectRoot() string {
	if x != nil {
		return x.ProjectRoot
	}
	return ""
}

func (x *SCIPProjectPlan) GetIndexer() string {
	if x != nil {
		return x.Indexer
	}
	return ""
}

func (x *SCIPProjectPlan) GetScipWorkerClass() string {
	if x != nil {
		return x.ScipWorkerClass
	}
	return ""
}

func (x *SCIPProjectPlan) GetToolchainDigest() string {
	if x != nil && x.ToolchainDigest != nil {
		return *x.ToolchainDigest
	}
	return ""
}

func (x *SCIPProjectPlan) GetImageDigest() string {
	if x != nil && x.ImageDigest != nil {
		return *x.ImageDigest
	}
	return ""
}

func (x *SCIPProjectPlan) GetProjectInputHash() string {
	if x != nil && x.ProjectInputHash != nil {
		return *x.ProjectInputHash
	}
	return ""
}

type IndexPlanRevision struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId      string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Branch           string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Revision         string                 `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	CommitHash       string                 `protobuf:"bytes,4,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	RunAstTreeSitter bool                   `protobuf:"varint,5,opt,name=run_ast_tree_sitter,json=runAstTreeSitter,proto3" json:"run_ast_tree_sitter,omitempty"`
	RunGraphMerge    bool                   `protobuf:"varint,6,opt,name=run_graph_merge,json=runGraphMerge,proto3" json:"run_graph_merge,omitempty"`
	RunActivate      bool                   `protobuf:"varint,7,opt,name=run_activate,json=runActivate,proto3" json:"run_activate,omitempty"`
	ScipProjects     []*SCIPProjectPlan     `protobuf:"bytes,8,rep,name=scip_projects,json=scipProjects,proto3" json:"scip_projects,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IndexPlanRevision) Reset() {
	*x = IndexPlanRevision{}
	mi := &file_codeintel_v1_index_plan_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexPlanRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexPlanRevision) ProtoMessage() {}

func (x *IndexPlanRevision) ProtoReflect() protoreflect.Message {
	mi := &file_codeintel_v1_index_plan_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexPlanRevision.ProtoReflect.Descriptor instead.
func (*IndexPlanRevision) Descriptor() ([]byte, []int) {
	return file_codeintel_v1_index_plan_service_proto_rawDescGZIP(), []int{1}
}

func (x *IndexPlanRevision) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *IndexPlanRevision) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *IndexPlanRevision) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *IndexPlanRevision) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *IndexPlanRevision) GetRunAstTreeSitter() bool {
	if x != nil {
		return x.RunAstTreeSitter
	}
	return false
}

func (x *IndexPlanRevision) GetRunGraphMerge() bool {
	if x != nil {
		return x.RunGraphMerge
	}
	return false
}

func (x *IndexPlanRevision) GetRunActivate() bool {
	if x != nil {
		return x.RunActivate
	}
	return false
}

func (x *IndexPlanRevision) GetScipProjects() []*SCIPProjectPlan {
	if x != nil {
		return x.ScipProjects
	}
	return nil
}

type WriteIndexPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexJobId    string                 `protobuf:"bytes,1,opt,name=index_job_id,json=indexJobId,proto3" json:"index_job_id,omitempty"`
	OrgId         int32                  `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	RepoId        int32                  `protobuf:"varint,3,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,4,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	Revisions     []*IndexPlanRevision   `protobuf:"bytes,5,rep,name=revisions,proto3" json:"revisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteIndexPlanRequest) Reset() {
	*x = WriteIndexPlanRequest{}
	mi := &file_codeintel_v1_index_plan_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteIndexPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteIndexPlanRequest) ProtoMessage() {}

func (x *WriteIndexPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codeintel_v1_index_plan_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteIndexPlanRequest.ProtoReflect.Descriptor instead.
func (*WriteIndexPlanRequest) Descriptor() ([]byte, []int) {
	return file_codeintel_v1_index_plan_service_proto_rawDescGZIP(), []int{2}
}

func (x *WriteIndexPlanRequest) GetIndexJobId() string {
	if x != nil {
		return x.IndexJobId
	}
	return ""
}

func (x *WriteIndexPlanRequest) GetOrgId() int32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *WriteIndexPlanRequest) GetRepoId() int32 {
	if x != nil {
		return x.RepoId
	}
	return 0
}

func (x *WriteIndexPlanRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *WriteIndexPlanRequest) GetRevisions() []*IndexPlanRevision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

type WriteIndexPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevisionCount int32                  `protobuf:"varint,1,opt,name=revision_count,json=revisionCount,proto3" json:"revision_count,omitempty"`
	SubjobCount   int32                  `protobuf:"varint,2,opt,name=subjob_count,json=subjobCount,proto3" json:"subjob_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteIndexPlanResponse) Reset() {
	*x = WriteIndexPlanResponse{}
	mi := &file_codeintel_v1_index_plan_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteIndexPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteIndexPlanResponse) ProtoMessage() {}

func (x *WriteIndexPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codeintel_v1_index_plan_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteIndexPlanResponse.ProtoReflect.Descriptor instead.
func (*WriteIndexPlanResponse) Descriptor() ([]byte, []int) {
	return file_codeintel_v1_index_plan_service_proto_rawDescGZIP(), []int{3}
}

func (x *WriteIndexPlanResponse) GetRevisionCount() int32 {
	if x != nil {
		return x.RevisionCount
	}
	return 0
}

func (x *WriteIndexPlanResponse) GetSubjobCount() int32 {
	if x != nil {
		return x.SubjobCount
	}
	return 0
}

var File_codeintel_v1_index_plan_service_proto protoreflect.FileDescriptor

const file_codeintel_v1_index_plan_service_proto_rawDesc = "" +
	"\n" +
	"%codeintel/v1/index_plan_service.proto\x12\fcodeintel.v1\"\xde\x02\n" +
	"\x0fSCIPProjectPlan\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12!\n" +
	"\fproject_root\x18\x02 \x01(\tR\vprojectRoot\x12\x18\n" +
	"\aindexer\x18\x03 \x01(\tR\aindexer\x12*\n" +
	"\x11scip_worker_class\x18\x04 \x01(\tR\x0fscipWorkerClass\x12.\n" +
	"\x10toolchain_digest\x18\x05 \x01(\tH\x00R\x0ftoolchainDigest\x88\x01\x01\x12&\n" +
	"\fimage_digest\x18\x06 \x01(\tH\x01R\vimageDigest\x88\x01\x01\x121\n" +
	"\x12project_input_hash\x18\a \x01(\tH\x02R\x10projectInputHash\x88\x01\x01B\x13\n" +
	"\x11_toolchain_digestB\x0f\n" +
	"\r_image_digestB\x15\n" +
	"\x13_project_input_hash\"\xc9\x02\n" +
	"\x11IndexPlanRevision\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\x12\x1f\n" +
	"\vcommit_hash\x18\x04 \x01(\tR\n" +
	"commitHash\x12-\n" +
	"\x13run_ast_tree_sitter\x18\x05 \x01(\bR\x10runAstTreeSitter\x12&\n" +
	"\x0frun_graph_merge\x18\x06 \x01(\bR\rrunGraphMerge\x12!\n" +
	"\frun_activate\x18\a \x01(\bR\vrunActivate\x12B\n" +
	"\rscip_projects\x18\b \x03(\v2\x1d.codeintel.v1.SCIPProjectPlanR\fscipProjects\"\xcb\x01\n" +
	"\x15WriteIndexPlanRequest\x12 \n" +
	"\findex_job_id\x18\x01 \x01(\tR\n" +
	"indexJobId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\x05R\x05orgId\x12\x17\n" +
	"\arepo_id\x18\x03 \x01(\x05R\x06repoId\x12!\n" +
	"\fmax_attempts\x18\x04 \x01(\x05R\vmaxAttempts\x12=\n" +
	"\trevisions\x18\x05 \x03(\v2\x1f.codeintel.v1.IndexPlanRevisionR\trevisions\"b\n" +
	"\x16WriteIndexPlanResponse\x12%\n" +
	"\x0erevision_count\x18\x01 \x01(\x05R\rrevisionCount\x12!\n" +
	"\fsubjob_count\x18\x02 \x01(\x05R\vsubjobCount2l\n" +
	"\x10IndexPlanService\x12X\n" +
	"\tWritePlan\x12#.codeintel.v1.WriteIndexPlanRequest\x1a$.codeintel.v1.WriteIndexPlanResponse\"\x00B*Z(codeintel/proto/codeintel/v1;codeintelv1b\x06proto3"

var (
	file_codeintel_v1_index_plan_service_proto_rawDescOnce sync.Once
	file_codeintel_v1_index_plan_service_proto_rawDescData []byte
)

func file_codeintel_v1_index_plan_service_proto_rawDescGZIP() []byte {
	file_codeintel_v1_index_plan_service_proto_rawDescOnce.Do(func() {
		file_codeintel_v1_index_plan_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codeintel_v1_index_plan_service_proto_rawDesc), len(file_codeintel_v1_index_plan_service_proto_rawDesc)))
	})
	return file_codeintel_v1_index_plan_service_proto_rawDescData
}

var file_codeintel_v1_index_plan_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_codeintel_v1_index_plan_service_proto_goTypes = []any{
	(*SCIPProjectPlan)(nil),        // 0: codeintel.v1.SCIPProjectPlan
	(*IndexPlanRevision)(nil),      // 1: codeintel.v1.IndexPlanRevision
	(*WriteIndexPlanRequest)(nil),  // 2: codeintel.v1.WriteIndexPlanRequest
	(*WriteIndexPlanResponse)(nil), // 3: codeintel.v1.WriteIndexPlanResponse
}
var file_codeintel_v1_index_plan_service_proto_depIdxs = []int32{
	0, // 0: codeintel.v1.IndexPlanRevision.scip_projects:type_name -> codeintel.v1.SCIPProjectPlan
	1, // 1: codeintel.v1.WriteIndexPlanRequest.revisions:type_name -> codeintel.v1.IndexPlanRevision
	2, // 2: codeintel.v1.IndexPlanService.WritePlan:input_type -> codeintel.v1.WriteIndexPlanRequest
	3, // 3: codeintel.v1.IndexPlanService.WritePlan:output_type -> codeintel.v1.WriteIndexPlanResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_codeintel_v1_index_plan_service_proto_init() }
func file_codeintel_v1_index_plan_service_proto_init() {
	if File_codeintel_v1_index_plan_service_proto != nil {
		return
	}
	file_codeintel_v1_index_plan_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codeintel_v1_index_plan_service_proto_rawDesc), len(file_codeintel_v1_index_plan_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_codeintel_v1_index_plan_service_proto_goTypes,
		DependencyIndexes: file_codeintel_v1_index_plan_service_proto_depIdxs,
		MessageInfos:      file_codeintel_v1_index_plan_service_proto_msgTypes,
	}.Build()
	File_codeintel_v1_index_plan_service_proto = out.File
	file_codeintel_v1_index_plan_service_proto_goTypes = nil
	file_codeintel_v1_index_plan_service_proto_depIdxs = nil
}
