// IndexExecutorService is the backend-to-indexer execution contract for
// one durable indexing subjob. Backend owns queue claim, heartbeat,
// artifact validation, and persistence; the indexer owns CPU-heavy
// extraction for the assigned layer.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: codeintel/v1/index_executor_service.proto

package codeintelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteIndexSubjobRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubjobId          string                 `protobuf:"bytes,1,opt,name=subjob_id,json=subjobId,proto3" json:"subjob_id,omitempty"`
	RepoIndexingJobId string                 `protobuf:"bytes,2,opt,name=repo_indexing_job_id,json=repoIndexingJobId,proto3" json:"repo_indexing_job_id,omitempty"`
	OrgId             int32                  `protobuf:"varint,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	WorkspaceId       string                 `protobuf:"bytes,4,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	RepoId            int32                  `protobuf:"varint,5,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Branch            string                 `protobuf:"bytes,6,opt,name=branch,proto3" json:"branch,omitempty"`
	Revision          string                 `protobuf:"bytes,7,opt,name=revision,proto3" json:"revision,omitempty"`
	CommitHash        string                 `protobuf:"bytes,8,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	Layer             string                 `protobuf:"bytes,9,opt,name=layer,proto3" json:"layer,omitempty"`
	Language          *string                `protobuf:"bytes,10,opt,name=language,proto3,oneof" json:"language,omitempty"`
	ProjectRoot       *string                `protobuf:"bytes,11,opt,name=project_root,json=projectRoot,proto3,oneof" json:"project_root,omitempty"`
	Indexer           *string                `protobuf:"bytes,12,opt,name=indexer,proto3,oneof" json:"indexer,omitempty"`
	WorkerClass       string                 `protobuf:"bytes,13,opt,name=worker_class,json=workerClass,proto3" json:"worker_class,omitempty"`
	QueueName         string                 `protobuf:"bytes,14,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Attempt           int32                  `protobuf:"varint,15,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecuteIndexSubjobRequest) Reset() {
	*x = ExecuteIndexSubjobRequest{}
	mi := &file_codeintel_v1_index_executor_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteIndexSubjobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteIndexSubjobRequest) ProtoMessage() {}

func (x *ExecuteIndexSubjobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codeintel_v1_index_executor_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteIndexSubjobRequest.ProtoReflect.Descriptor instead.
func (*ExecuteIndexSubjobRequest) Descriptor() ([]byte, []int) {
	return file_codeintel_v1_index_executor_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteIndexSubjobRequest) GetSubjobId() string {
	if x != nil {
		return x.SubjobId
	}
	return ""
}

func (x *ExecuteIndexSubjobRequest) GetRepoIndexingJobId() string {
	if x != nil {
		return x.RepoIndexingJobId
	}
	return ""
}

func (x *ExecuteIndexSubjobRequest) GetOrgId() int32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *ExecuteIndexSubjobRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ExecuteIndexSubjobRequest) GetRepoId() int32 {
	if x != nil {
		return x.RepoId
	}
	return 0
}

func (x *ExecuteIndexSubjobRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ExecuteIndexSubjobRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *ExecuteIndexSubjobRequest) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *ExecuteIndexSubjobRequest) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *ExecuteIndexSubjobRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *ExecuteIndexSubjobRequest) GetProjectRoot() string {
	if x != nil && x.ProjectRoot != nil {
		return *x.ProjectRoot
	}
	return ""
}

func (x *ExecuteIndexSubjobRequest) GetIndexer() string {
	if x != nil && x.Indexer != nil {
		return *x.Indexer
	}
	return ""
}

func (x *ExecuteIndexSubjobRequest) GetWorkerClass() string {
	if x != nil {
		return x.WorkerClass
	}
	return ""
}

func (x *ExecuteIndexSubjobRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *ExecuteIndexSubjobRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type ExecuteIndexSubjobResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ArtifactTempPath string                 `protobuf:"bytes,1,opt,name=artifact_temp_path,json=artifactTempPath,proto3" json:"artifact_temp_path,omitempty"`
	ArtifactPath     string                 `protobuf:"bytes,2,opt,name=artifact_path,json=artifactPath,proto3" json:"artifact_path,omitempty"`
	ArtifactSha256   string                 `protobuf:"bytes,3,opt,name=artifact_sha256,json=artifactSha256,proto3" json:"artifact_sha256,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecuteIndexSubjobResponse) Reset() {
	*x = ExecuteIndexSubjobResponse{}
	mi := &file_codeintel_v1_index_executor_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteIndexSubjobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteIndexSubjobResponse) ProtoMessage() {}

func (x *ExecuteIndexSubjobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codeintel_v1_index_executor_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteIndexSubjobResponse.ProtoReflect.Descriptor instead.
func (*ExecuteIndexSubjobResponse) Descriptor() ([]byte, []int) {
	return file_codeintel_v1_index_executor_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteIndexSubjobResponse) GetArtifactTempPath() string {
	if x != nil {
		return x.ArtifactTempPath
	}
	return ""
}

func (x *ExecuteIndexSubjobResponse) GetArtifactPath() string {
	if x != nil {
		return x.ArtifactPath
	}
	return ""
}

func (x *ExecuteIndexSubjobResponse) GetArtifactSha256() string {
	if x != nil {
		return x.ArtifactSha256
	}
	return ""
}

func (x *ExecuteIndexSubjobResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_codeintel_v1_index_executor_service_proto protoreflect.FileDescriptor

const file_codeintel_v1_index_executor_service_proto_rawDesc = "" +
	"\n" +
	")codeintel/v1/index_executor_service.proto\x12\fcodeintel.v1\"\x95\x04\n" +
	"\x19ExecuteIndexSubjobRequest\x12\x1b\n" +
	"\tsubjob_id\x18\x01 \x01(\tR\bsubjobId\x12/\n" +
	"\x14repo_indexing_job_id\x18\x02 \x01(\tR\x11repoIndexingJobId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\x05R\x05orgId\x12!\n" +
	"\fworkspace_id\x18\x04 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\arepo_id\x18\x05 \x01(\x05R\x06repoId\x12\x16\n" +
	"\x06branch\x18\x06 \x01(\tR\x06branch\x12\x1a\n" +
	"\brevision\x18\a \x01(\tR\brevision\x12\x1f\n" +
	"\vcommit_hash\x18\b \x01(\tR\n" +
	"commitHash\x12\x14\n" +
	"\x05layer\x18\t \x01(\tR\x05layer\x12\x1f\n" +
	"\blanguage\x18\n" +
	" \x01(\tH\x00R\blanguage\x88\x01\x01\x12&\n" +
	"\fproject_root\x18\v \x01(\tH\x01R\vprojectRoot\x88\x01\x01\x12\x1d\n" +
	"\aindexer\x18\f \x01(\tH\x02R\aindexer\x88\x01\x01\x12!\n" +
	"\fworker_class\x18\r \x01(\tR\vworkerClass\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x0e \x01(\tR\tqueueName\x12\x18\n" +
	"\aattempt\x18\x0f \x01(\x05R\aattemptB\v\n" +
	"\t_languageB\x0f\n" +
	"\r_project_rootB\n" +
	"\n" +
	"\b_indexer\"\xa9\x02\n" +
	"\x1aExecuteIndexSubjobResponse\x12,\n" +
	"\x12artifact_temp_path\x18\x01 \x01(\tR\x10artifactTempPath\x12#\n" +
	"\rartifact_path\x18\x02 \x01(\tR\fartifactPath\x12'\n" +
	"\x0fartifact_sha256\x18\x03 \x01(\tR\x0eartifactSha256\x12R\n" +
	"\bmetadata\x18\x04 \x03(\v26.codeintel.v1.ExecuteIndexSubjobResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012|\n" +
	"\x14IndexExecutorService\x12d\n" +
	"\rExecuteSubjob\x12'.codeintel.v1.ExecuteIndexSubjobRequest\x1a(.codeintel.v1.ExecuteIndexSubjobResponse\"\x00B*Z(codeintel/proto/codeintel/v1;codeintelv1b\x06proto3"

var (
	file_codeintel_v1_index_executor_service_proto_rawDescOnce sync.Once
	file_codeintel_v1_index_executor_service_proto_rawDescData []byte
)

func file_codeintel_v1_index_executor_service_proto_rawDescGZIP() []byte {
	file_codeintel_v1_index_executor_service_proto_rawDescOnce.Do(func() {
		file_codeintel_v1_index_executor_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codeintel_v1_index_executor_service_proto_rawDesc), len(file_codeintel_v1_index_executor_service_proto_rawDesc)))
	})
	return file_codeintel_v1_index_executor_service_proto_rawDescData
}

var file_codeintel_v1_index_executor_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_codeintel_v1_index_executor_service_proto_goTypes = []any{
	(*ExecuteIndexSubjobRequest)(nil),  // 0: codeintel.v1.ExecuteIndexSubjobRequest
	(*ExecuteIndexSubjobResponse)(nil), // 1: codeintel.v1.ExecuteIndexSubjobResponse
	nil,                                // 2: codeintel.v1.ExecuteIndexSubjobResponse.MetadataEntry
}
var file_codeintel_v1_index_executor_service_proto_depIdxs = []int32{
	2, // 0: codeintel.v1.ExecuteIndexSubjobResponse.metadata:type_name -> codeintel.v1.ExecuteIndexSubjobResponse.MetadataEntry
	0, // 1: codeintel.v1.IndexExecutorService.ExecuteSubjob:input_type -> codeintel.v1.ExecuteIndexSubjobRequest
	1, // 2: codeintel.v1.IndexExecutorService.ExecuteSubjob:output_type -> codeintel.v1.ExecuteIndexSubjobResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_codeintel_v1_index_executor_service_proto_init() }
func file_codeintel_v1_index_executor_service_proto_init() {
	if File_codeintel_v1_index_executor_service_proto != nil {
		return
	}
	file_codeintel_v1_index_executor_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codeintel_v1_index_executor_service_proto_rawDesc), len(file_codeintel_v1_index_executor_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_codeintel_v1_index_executor_service_proto_goTypes,
		DependencyIndexes: file_codeintel_v1_index_executor_service_proto_depIdxs,
		MessageInfos:      file_codeintel_v1_index_executor_service_proto_msgTypes,
	}.Build()
	File_codeintel_v1_index_executor_service_proto = out.File
	file_codeintel_v1_index_executor_service_proto_goTypes = nil
	file_codeintel_v1_index_executor_service_proto_depIdxs = nil
}
