// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: scip/v1/scip.proto

package scippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PositionEncoding int32

const (
	PositionEncoding_POSITION_ENCODING_UNSPECIFIED          PositionEncoding = 0
	PositionEncoding_UTF8_CODE_UNIT_OFFSET_FROM_LINE_START  PositionEncoding = 1
	PositionEncoding_UTF16_CODE_UNIT_OFFSET_FROM_LINE_START PositionEncoding = 2
	PositionEncoding_UTF32_CODE_UNIT_OFFSET_FROM_LINE_START PositionEncoding = 3
)

// Enum value maps for PositionEncoding.
var (
	PositionEncoding_name = map[int32]string{
		0: "POSITION_ENCODING_UNSPECIFIED",
		1: "UTF8_CODE_UNIT_OFFSET_FROM_LINE_START",
		2: "UTF16_CODE_UNIT_OFFSET_FROM_LINE_START",
		3: "UTF32_CODE_UNIT_OFFSET_FROM_LINE_START",
	}
	PositionEncoding_value = map[string]int32{
		"POSITION_ENCODING_UNSPECIFIED":          0,
		"UTF8_CODE_UNIT_OFFSET_FROM_LINE_START":  1,
		"UTF16_CODE_UNIT_OFFSET_FROM_LINE_START": 2,
		"UTF32_CODE_UNIT_OFFSET_FROM_LINE_START": 3,
	}
)

func (x PositionEncoding) Enum() *PositionEncoding {
	p := new(PositionEncoding)
	*p = x
	return p
}

func (x PositionEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PositionEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_scip_v1_scip_proto_enumTypes[0].Descriptor()
}

func (PositionEncoding) Type() protoreflect.EnumType {
	return &file_scip_v1_scip_proto_enumTypes[0]
}

func (x PositionEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PositionEncoding.Descriptor instead.
func (PositionEncoding) EnumDescriptor() ([]byte, []int) {
	return file_scip_v1_scip_proto_rawDescGZIP(), []int{0}
}

type SymbolRole int32

const (
	SymbolRole_SYMBOL_ROLE_UNSPECIFIED SymbolRole = 0
	SymbolRole_DEFINITION              SymbolRole = 1
	SymbolRole_IMPORT                  SymbolRole = 2
	SymbolRole_WRITE_ACCESS            SymbolRole = 4
	SymbolRole_READ_ACCESS             SymbolRole = 8
	SymbolRole_GENERATED               SymbolRole = 16
	SymbolRole_TEST                    SymbolRole = 32
	SymbolRole_FORWARD_DEFINITION      SymbolRole = 64
)

// Enum value maps for SymbolRole.
var (
	SymbolRole_name = map[int32]string{
		0:  "SYMBOL_ROLE_UNSPECIFIED",
		1:  "DEFINITION",
		2:  "IMPORT",
		4:  "WRITE_ACCESS",
		8:  "READ_ACCESS",
		16: "GENERATED",
		32: "TEST",
		64: "FORWARD_DEFINITION",
	}
	SymbolRole_value = map[string]int32{
		"SYMBOL_ROLE_UNSPECIFIED": 0,
		"DEFINITION":              1,
		"IMPORT":                  2,
		"WRITE_ACCESS":            4,
		"READ_ACCESS":             8,
		"GENERATED":               16,
		"TEST":                    32,
		"FORWARD_DEFINITION":      64,
	}
)

func (x SymbolRole) Enum() *SymbolRole {
	p := new(SymbolRole)
	*p = x
	return p
}

func (x SymbolRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SymbolRole) Descriptor() protoreflect.EnumDescriptor {
	return file_scip_v1_scip_proto_enumTypes[1].Descriptor()
}

func (SymbolRole) Type() protoreflect.EnumType {
	return &file_scip_v1_scip_proto_enumTypes[1]
}

func (x SymbolRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SymbolRole.Descriptor instead.
func (SymbolRole) EnumDescriptor() ([]byte, []int) {
	return file_scip_v1_scip_proto_rawDescGZIP(), []int{1}
}

type SyntaxKind int32

const (
	SyntaxKind_SYNTAX_KIND_UNSPECIFIED        SyntaxKind = 0
	SyntaxKind_COMMENT                        SyntaxKind = 1
	SyntaxKind_PUNCTUATION_DELIMITER          SyntaxKind = 2
	SyntaxKind_PUNCTUATION_BRACKET            SyntaxKind = 3
	SyntaxKind_KEYWORD                        SyntaxKind = 4
	SyntaxKind_IDENTIFIER_OPERATOR            SyntaxKind = 5
	SyntaxKind_IDENTIFIER                     SyntaxKind = 6
	SyntaxKind_IDENTIFIER_BUILTIN             SyntaxKind = 7
	SyntaxKind_IDENTIFIER_NULL                SyntaxKind = 8
	SyntaxKind_IDENTIFIER_CONSTANT            SyntaxKind = 9
	SyntaxKind_IDENTIFIER_MUTABLE_GLOBAL      SyntaxKind = 10
	SyntaxKind_IDENTIFIER_PARAMETER           SyntaxKind = 11
	SyntaxKind_IDENTIFIER_LOCAL               SyntaxKind = 12
	SyntaxKind_IDENTIFIER_SHADOWED            SyntaxKind = 13
	SyntaxKind_IDENTIFIER_NAMESPACE           SyntaxKind = 14
	SyntaxKind_IDENTIFIER_FUNCTION            SyntaxKind = 15
	SyntaxKind_IDENTIFIER_FUNCTION_DEFINITION SyntaxKind = 16
	SyntaxKind_IDENTIFIER_MACRO               SyntaxKind = 17
	SyntaxKind_IDENTIFIER_MACRO_DEFINITION    SyntaxKind = 18
	SyntaxKind_IDENTIFIER_TYPE                SyntaxKind = 19
	SyntaxKind_IDENTIFIER_BUILTIN_TYPE        SyntaxKind = 20
	SyntaxKind_IDENTIFIER_ATTRIBUTE           SyntaxKind = 21
	SyntaxKind_REGEX_ESCAPE                   SyntaxKind = 22
	SyntaxKind_REGEX_REPEATED                 SyntaxKind = 23
	SyntaxKind_REGEX_WILDCARD                 SyntaxKind = 24
	SyntaxKind_REGEX_DELIMITER                SyntaxKind = 25
	SyntaxKind_REGEX_JOIN                     SyntaxKind = 26
	SyntaxKind_STRING_LITERAL                 SyntaxKind = 27
	SyntaxKind_STRING_LITERAL_ESCAPE          SyntaxKind = 28
	SyntaxKind_STRING_LITERAL_SPECIAL         SyntaxKind = 29
	SyntaxKind_STRING_LITERAL_KEY             SyntaxKind = 30
	SyntaxKind_CHARACTER_LITERAL              SyntaxKind = 31
	SyntaxKind_NUMERIC_LITERAL                SyntaxKind = 32
	SyntaxKind_BOOLEAN_LITERAL                SyntaxKind = 33
	SyntaxKind_TAG                            SyntaxKind = 34
	SyntaxKind_TAG_ATTRIBUTE                  SyntaxKind = 35
	SyntaxKind_TAG_DELIMITER                  SyntaxKind = 36
)

// Enum value maps for SyntaxKind.
var (
	SyntaxKind_name = map[int32]string{
		0:  "SYNTAX_KIND_UNSPECIFIED",
		1:  "COMMENT",
		2:  "PUNCTUATION_DELIMITER",
		3:  "PUNCTUATION_BRACKET",
		4:  "KEYWORD",
		5:  "IDENTIFIER_OPERATOR",
		6:  "IDENTIFIER",
		7:  "IDENTIFIER_BUILTIN",
		8:  "IDENTIFIER_NULL",
		9:  "IDENTIFIER_CONSTANT",
		10: "IDENTIFIER_MUTABLE_GLOBAL",
		11: "IDENTIFIER_PARAMETER",
		12: "IDENTIFIER_LOCAL",
		13: "IDENTIFIER_SHADOWED",
		14: "IDENTIFIER_NAMESPACE",
		15: "IDENTIFIER_FUNCTION",
		16: "IDENTIFIER_FUNCTION_DEFINITION",
		17: "IDENTIFIER_MACRO",
		18: "IDENTIFIER_MACRO_DEFINITION",
		19: "IDENTIFIER_TYPE",
		20: "IDENTIFIER_BUILTIN_TYPE",
		21: "IDENTIFIER_ATTRIBUTE",
		22: "REGEX_ESCAPE",
		23: "REGEX_REPEATED",
		24: "REGEX_WILDCARD",
		25: "REGEX_DELIMITER",
		26: "REGEX_JOIN",
		27: "STRING_LITERAL",
		28: "STRING_LITERAL_ESCAPE",
		29: "STRING_LITERAL_SPECIAL",
		30: "STRING_LITERAL_KEY",
		31: "CHARACTER_LITERAL",
		32: "NUMERIC_LITERAL",
		33: "BOOLEAN_LITERAL",
		34: "TAG",
		35: "TAG_ATTRIBUTE",
		36: "TAG_DELIMITER",
	}
	SyntaxKind_value = map[string]int32{
		"SYNTAX_KIND_UNSPECIFIED":        0,
		"COMMENT":                        1,
		"PUNCTUATION_DELIMITER":          2,
		"PUNCTUATION_BRACKET":            3,
		"KEYWORD":                        4,
		"IDENTIFIER_OPERATOR":            5,
		"IDENTIFIER":                     6,
		"IDENTIFIER_BUILTIN":             7,
		"IDENTIFIER_NULL":                8,
		"IDENTIFIER_CONSTANT":            9,
		"IDENTIFIER_MUTABLE_GLOBAL":      10,
		"IDENTIFIER_PARAMETER":           11,
		"IDENTIFIER_LOCAL":               12,
		"IDENTIFIER_SHADOWED":            13,
		"IDENTIFIER_NAMESPACE":           14,
		"IDENTIFIER_FUNCTION":            15,
		"IDENTIFIER_FUNCTION_DEFINITION": 16,
		"IDENTIFIER_MACRO":               17,
		"IDENTIFIER_MACRO_DEFINITION":    18,
		"IDENTIFIER_TYPE":                19,
		"IDENTIFIER_BUILTIN_TYPE":        20,
		"IDENTIFIER_ATTRIBUTE":           21,
		"REGEX_ESCAPE":                   22,
		"REGEX_REPEATED":                 23,
		"REGEX_WILDCARD":                 24,
		"REGEX_DELIMITER":                25,
		"REGEX_JOIN":                     26,
		"STRING_LITERAL":                 27,
		"STRING_LITERAL_ESCAPE":          28,
		"STRING_LITERAL_SPECIAL":         29,
		"STRING_LITERAL_KEY":             30,
		"CHARACTER_LITERAL":              31,
		"NUMERIC_LITERAL":                32,
		"BOOLEAN_LITERAL":                33,
		"TAG":                            34,
		"TAG_ATTRIBUTE":                  35,
		"TAG_DELIMITER":                  36,
	}
)

func (x SyntaxKind) Enum() *SyntaxKind {
	p := new(SyntaxKind)
	*p = x
	return p
}

func (x SyntaxKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyntaxKind) Descriptor() protoreflect.EnumDescriptor {
	return file_scip_v1_scip_proto_enumTypes[2].Descriptor()
}

func (SyntaxKind) Type() protoreflect.EnumType {
	return &file_scip_v1_scip_proto_enumTypes[2]
}

func (x SyntaxKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyntaxKind.Descriptor instead.
func (SyntaxKind) EnumDescriptor() ([]byte, []int) {
	return file_scip_v1_scip_proto_rawDescGZIP(), []int{2}
}

type SymbolInformation_Kind int32

const (
	SymbolInformation_KIND_UNSPECIFIED     SymbolInformation_Kind = 0
	SymbolInformation_ARRAY                SymbolInformation_Kind = 1
	SymbolInformation_ASSERTION            SymbolInformation_Kind = 2
	SymbolInformation_ASSOCIATED_TYPE      SymbolInformation_Kind = 3
	SymbolInformation_ATTRIBUTE            SymbolInformation_Kind = 4
	SymbolInformation_AXIOM                SymbolInformation_Kind = 5
	SymbolInformation_BOOLEAN              SymbolInformation_Kind = 6
	SymbolInformation_CLASS                SymbolInformation_Kind = 7
	SymbolInformation_CONSTANT             SymbolInformation_Kind = 8
	SymbolInformation_CONSTRUCTOR          SymbolInformation_Kind = 9
	SymbolInformation_DATA_FAMILY          SymbolInformation_Kind = 10
	SymbolInformation_ENUM                 SymbolInformation_Kind = 11
	SymbolInformation_ENUM_MEMBER          SymbolInformation_Kind = 12
	SymbolInformation_EVENT                SymbolInformation_Kind = 13
	SymbolInformation_FACT                 SymbolInformation_Kind = 14
	SymbolInformation_FIELD                SymbolInformation_Kind = 15
	SymbolInformation_FILE                 SymbolInformation_Kind = 16
	SymbolInformation_FUNCTION             SymbolInformation_Kind = 17
	SymbolInformation_GETTER               SymbolInformation_Kind = 18
	SymbolInformation_GRAMMAR              SymbolInformation_Kind = 19
	SymbolInformation_INSTANCE             SymbolInformation_Kind = 20
	SymbolInformation_INTERFACE            SymbolInformation_Kind = 21
	SymbolInformation_KEY                  SymbolInformation_Kind = 22
	SymbolInformation_LANG                 SymbolInformation_Kind = 23
	SymbolInformation_LEMMA                SymbolInformation_Kind = 24
	SymbolInformation_MACRO                SymbolInformation_Kind = 25
	SymbolInformation_METHOD               SymbolInformation_Kind = 26
	SymbolInformation_METHOD_RECEIVER      SymbolInformation_Kind = 27
	SymbolInformation_MESSAGE              SymbolInformation_Kind = 28
	SymbolInformation_MODULE               SymbolInformation_Kind = 29
	SymbolInformation_NAMESPACE            SymbolInformation_Kind = 30
	SymbolInformation_NULL_KIND            SymbolInformation_Kind = 31
	SymbolInformation_NUMBER               SymbolInformation_Kind = 32
	SymbolInformation_OBJECT               SymbolInformation_Kind = 33
	SymbolInformation_OPERATOR             SymbolInformation_Kind = 34
	SymbolInformation_PACKAGE              SymbolInformation_Kind = 35
	SymbolInformation_PACKAGE_OBJECT       SymbolInformation_Kind = 36
	SymbolInformation_PARAMETER            SymbolInformation_Kind = 37
	SymbolInformation_PARAMETER_LABEL      SymbolInformation_Kind = 38
	SymbolInformation_PATTERN              SymbolInformation_Kind = 39
	SymbolInformation_PREDICATE            SymbolInformation_Kind = 40
	SymbolInformation_PROPERTY             SymbolInformation_Kind = 41
	SymbolInformation_PROTOCOL             SymbolInformation_Kind = 42
	SymbolInformation_QUASIQUOTER          SymbolInformation_Kind = 43
	SymbolInformation_SELF_PARAMETER       SymbolInformation_Kind = 44
	SymbolInformation_SETTER               SymbolInformation_Kind = 45
	SymbolInformation_SIGNATURE            SymbolInformation_Kind = 46
	SymbolInformation_SUBSCRIPT            SymbolInformation_Kind = 47
	SymbolInformation_STRING               SymbolInformation_Kind = 48
	SymbolInformation_STRUCT               SymbolInformation_Kind = 49
	SymbolInformation_TACTIC               SymbolInformation_Kind = 50
	SymbolInformation_THEOREM              SymbolInformation_Kind = 51
	SymbolInformation_THIS_PARAMETER       SymbolInformation_Kind = 52
	SymbolInformation_TRAIT                SymbolInformation_Kind = 53
	SymbolInformation_TYPE                 SymbolInformation_Kind = 54
	SymbolInformation_TYPE_ALIAS           SymbolInformation_Kind = 55
	SymbolInformation_TYPE_CLASS           SymbolInformation_Kind = 56
	SymbolInformation_TYPE_FAMILY          SymbolInformation_Kind = 57
	SymbolInformation_TYPE_PARAMETER       SymbolInformation_Kind = 58
	SymbolInformation_UNION                SymbolInformation_Kind = 59
	SymbolInformation_VALUE                SymbolInformation_Kind = 60
	SymbolInformation_VARIABLE             SymbolInformation_Kind = 61
	SymbolInformation_CONTRACT             SymbolInformation_Kind = 62
	SymbolInformation_ERROR                SymbolInformation_Kind = 63
	SymbolInformation_LIBRARY              SymbolInformation_Kind = 64
	SymbolInformation_MODIFIER             SymbolInformation_Kind = 65
	SymbolInformation_ABSTRACT_METHOD      SymbolInformation_Kind = 66
	SymbolInformation_METHOD_SPECIFICATION SymbolInformation_Kind = 67
	SymbolInformation_PROTOCOL_METHOD      SymbolInformation_Kind = 68
	SymbolInformation_PURE_VIRTUAL_METHOD  SymbolInformation_Kind = 69
	SymbolInformation_TRAIT_METHOD         SymbolInformation_Kind = 70
	SymbolInformation_TYPE_CLASS_METHOD    SymbolInformation_Kind = 71
	SymbolInformation_ACCESSOR             SymbolInformation_Kind = 72
	SymbolInformation_DELEGATE             SymbolInformation_Kind = 73
	SymbolInformation_METHOD_ALIAS         SymbolInformation_Kind = 74
	SymbolInformation_SINGLETON_CLASS      SymbolInformation_Kind = 75
	SymbolInformation_SINGLETON_METHOD     SymbolInformation_Kind = 76
	SymbolInformation_STATIC_DATA_MEMBER   SymbolInformation_Kind = 77
	SymbolInformation_STATIC_EVENT         SymbolInformation_Kind = 78
	SymbolInformation_STATIC_FIELD         SymbolInformation_Kind = 79
	SymbolInformation_STATIC_METHOD        SymbolInformation_Kind = 80
	SymbolInformation_STATIC_PROPERTY      SymbolInformation_Kind = 81
	SymbolInformation_STATIC_VARIABLE      SymbolInformation_Kind = 82
	SymbolInformation_EXTENSION            SymbolInformation_Kind = 84
	SymbolInformation_MIXIN                SymbolInformation_Kind = 85
	SymbolInformation_CONCEPT              SymbolInformation_Kind = 86
)

// Enum value maps for SymbolInformation_Kind.
var (
	SymbolInformation_Kind_name = map[int32]string{
		0:  "KIND_UNSPECIFIED",
		1:  "ARRAY",
		2:  "ASSERTION",
		3:  "ASSOCIATED_TYPE",
		4:  "ATTRIBUTE",
		5:  "AXIOM",
		6:  "BOOLEAN",
		7:  "CLASS",
		8:  "CONSTANT",
		9:  "CONSTRUCTOR",
		10: "DATA_FAMILY",
		11: "ENUM",
		12: "ENUM_MEMBER",
		13: "EVENT",
		14: "FACT",
		15: "FIELD",
		16: "FILE",
		17: "FUNCTION",
		18: "GETTER",
		19: "GRAMMAR",
		20: "INSTANCE",
		21: "INTERFACE",
		22: "KEY",
		23: "LANG",
		24: "LEMMA",
		25: "MACRO",
		26: "METHOD",
		27: "METHOD_RECEIVER",
		28: "MESSAGE",
		29: "MODULE",
		30: "NAMESPACE",
		31: "NULL_KIND",
		32: "NUMBER",
		33: "OBJECT",
		34: "OPERATOR",
		35: "PACKAGE",
		36: "PACKAGE_OBJECT",
		37: "PARAMETER",
		38: "PARAMETER_LABEL",
		39: "PATTERN",
		40: "PREDICATE",
		41: "PROPERTY",
		42: "PROTOCOL",
		43: "QUASIQUOTER",
		44: "SELF_PARAMETER",
		45: "SETTER",
		46: "SIGNATURE",
		47: "SUBSCRIPT",
		48: "STRING",
		49: "STRUCT",
		50: "TACTIC",
		51: "THEOREM",
		52: "THIS_PARAMETER",
		53: "TRAIT",
		54: "TYPE",
		55: "TYPE_ALIAS",
		56: "TYPE_CLASS",
		57: "TYPE_FAMILY",
		58: "TYPE_PARAMETER",
		59: "UNION",
		60: "VALUE",
		61: "VARIABLE",
		62: "CONTRACT",
		63: "ERROR",
		64: "LIBRARY",
		65: "MODIFIER",
		66: "ABSTRACT_METHOD",
		67: "METHOD_SPECIFICATION",
		68: "PROTOCOL_METHOD",
		69: "PURE_VIRTUAL_METHOD",
		70: "TRAIT_METHOD",
		71: "TYPE_CLASS_METHOD",
		72: "ACCESSOR",
		73: "DELEGATE",
		74: "METHOD_ALIAS",
		75: "SINGLETON_CLASS",
		76: "SINGLETON_METHOD",
		77: "STATIC_DATA_MEMBER",
		78: "STATIC_EVENT",
		79: "STATIC_FIELD",
		80: "STATIC_METHOD",
		81: "STATIC_PROPERTY",
		82: "STATIC_VARIABLE",
		84: "EXTENSION",
		85: "MIXIN",
		86: "CONCEPT",
	}
	SymbolInformation_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":     0,
		"ARRAY":                1,
		"ASSERTION":            2,
		"ASSOCIATED_TYPE":      3,
		"ATTRIBUTE":            4,
		"AXIOM":                5,
		"BOOLEAN":              6,
		"CLASS":                7,
		"CONSTANT":             8,
		"CONSTRUCTOR":          9,
		"DATA_FAMILY":          10,
		"ENUM":                 11,
		"ENUM_MEMBER":          12,
		"EVENT":                13,
		"FACT":                 14,
		"FIELD":                15,
		"FILE":                 16,
		"FUNCTION":             17,
		"GETTER":               18,
		"GRAMMAR":              19,
		"INSTANCE":             20,
		"INTERFACE":            21,
		"KEY":                  22,
		"LANG":                 23,
		"LEMMA":                24,
		"MACRO":                25,
		"METHOD":               26,
		"METHOD_RECEIVER":      27,
		"MESSAGE":              28,
		"MODULE":               29,
		"NAMESPACE":            30,
		"NULL_KIND":            31,
		"NUMBER":               32,
		"OBJECT":               33,
		"OPERATOR":             34,
		"PACKAGE":              35,
		"PACKAGE_OBJECT":       36,
		"PARAMETER":            37,
		"PARAMETER_LABEL":      38,
		"PATTERN":              39,
		"PREDICATE":            40,
		"PROPERTY":             41,
		"PROTOCOL":             42,
		"QUASIQUOTER":          43,
		"SELF_PARAMETER":       44,
		"SETTER":               45,
		"SIGNATURE":            46,
		"SUBSCRIPT":            47,
		"STRING":               48,
		"STRUCT":               49,
		"TACTIC":               50,
		"THEOREM":              51,
		"THIS_PARAMETER":       52,
		"TRAIT":                53,
		"TYPE":                 54,
		"TYPE_ALIAS":           55,
		"TYPE_CLASS":           56,
		"TYPE_FAMILY":          57,
		"TYPE_PARAMETER":       58,
		"UNION":                59,
		"VALUE":                60,
		"VARIABLE":             61,
		"CONTRACT":             62,
		"ERROR":                63,
		"LIBRARY":              64,
		"MODIFIER":             65,
		"ABSTRACT_METHOD":      66,
		"METHOD_SPECIFICATION": 67,
		"PROTOCOL_METHOD":      68,
		"PURE_VIRTUAL_METHOD":  69,
		"TRAIT_METHOD":         70,
		"TYPE_CLASS_METHOD":    71,
		"ACCESSOR":             72,
		"DELEGATE":             73,
		"METHOD_ALIAS":         74,
		"SINGLETON_CLASS":      75,
		"SINGLETON_METHOD":     76,
		"STATIC_DATA_MEMBER":   77,
		"STATIC_EVENT":         78,
		"STATIC_FIELD":         79,
		"STATIC_METHOD":        80,
		"STATIC_PROPERTY":      81,
		"STATIC_VARIABLE":      82,
		"EXTENSION":            84,
		"MIXIN":                85,
		"CONCEPT":              86,
	}
)

func (x SymbolInformation_Kind) Enum() *SymbolInformation_Kind {
	p := new(SymbolInformation_Kind)
	*p = x
	return p
}

func (x SymbolInformation_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SymbolInformation_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_scip_v1_scip_proto_enumTypes[3].Descriptor()
}

func (SymbolInformation_Kind) Type() protoreflect.EnumType {
	return &file_scip_v1_scip_proto_enumTypes[3]
}

func (x SymbolInformation_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SymbolInformation_Kind.Descriptor instead.
func (SymbolInformation_Kind) EnumDescriptor() ([]byte, []int) {
	return file_scip_v1_scip_proto_rawDescGZIP(), []int{3, 0}
}

type Index struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Documents       []*Document            `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	ExternalSymbols []*SymbolInformation   `protobuf:"bytes,3,rep,name=external_symbols,json=externalSymbols,proto3" json:"external_symbols,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_scip_v1_scip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_scip_v1_scip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_scip_v1_scip_proto_rawDescGZIP(), []int{0}
}

func (x *Index) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *Index) GetExternalSymbols() []*SymbolInformation {
	if x != nil {
		return x.ExternalSymbols
	}
	return nil
}

type Document struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RelativePath     string                 `protobuf:"bytes,1,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	Occurrences      []*Occurrence          `protobuf:"bytes,2,rep,name=occurrences,proto3" json:"occurrences,omitempty"`
	Symbols          []*SymbolInformation   `protobuf:"bytes,3,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Language         string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Text             string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	PositionEncoding PositionEncoding       `protobuf:"varint,6,opt,name=position_encoding,json=positionEncoding,proto3,enum=codeintel.scip.v1.PositionEncoding" json:"position_encoding,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_scip_v1_scip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_scip_v1_scip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_scip_v1_scip_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *Document) GetOccurrences() []*Occurrence {
	if x != nil {
		return x.Occurrences
	}
	return nil
}

func (x *Document) GetSymbols() []*SymbolInformation {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *Document) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Document) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Document) GetPositionEncoding() PositionEncoding {
	if x != nil {
		return x.PositionEncoding
	}
	return PositionEncoding_POSITION_ENCODING_UNSPECIFIED
}

type Occurrence struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Range                 []int32                `protobuf:"varint,1,rep,packed,name=range,proto3" json:"range,omitempty"`
	Symbol                string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	SymbolRoles           int32                  `protobuf:"varint,3,opt,name=symbol_roles,json=symbolRoles,proto3" json:"symbol_roles,omitempty"`
	OverrideDocumentation []string               `protobuf:"bytes,4,rep,name=override_documentation,json=overrideDocumentation,proto3" json:"override_documentation,omitempty"`
	SyntaxKind            SyntaxKind             `protobuf:"varint,5,opt,name=syntax_kind,json=syntaxKind,proto3,enum=codeintel.scip.v1.SyntaxKind" json:"syntax_kind,omitempty"`
	EnclosingRange        []int32                `protobuf:"varint,7,rep,packed,name=enclosing_range,json=enclosingRange,proto3" json:"enclosing_range,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Occurrence) Reset() {
	*x = Occurrence{}
	mi := &file_scip_v1_scip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Occurrence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Occurrence) ProtoMessage() {}

func (x *Occurrence) ProtoReflect() protoreflect.Message {
	mi := &file_scip_v1_scip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Occurrence.ProtoReflect.Descriptor instead.
func (*Occurrence) Descriptor() ([]byte, []int) {
	return file_scip_v1_scip_proto_rawDescGZIP(), []int{2}
}

func (x *Occurrence) GetRange() []int32 {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Occurrence) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Occurrence) GetSymbolRoles() int32 {
	if x != nil {
		return x.SymbolRoles
	}
	return 0
}

func (x *Occurrence) GetOverrideDocumentation() []string {
	if x != nil {
		return x.OverrideDocumentation
	}
	return nil
}

func (x *Occurrence) GetSyntaxKind() SyntaxKind {
	if x != nil {
		return x.SyntaxKind
	}
	return SyntaxKind_SYNTAX_KIND_UNSPECIFIED
}

func (x *Occurrence) GetEnclosingRange() []int32 {
	if x != nil {
		return x.EnclosingRange
	}
	return nil
}

type SymbolInformation struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Symbol                 string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Documentation          []string               `protobuf:"bytes,3,rep,name=documentation,proto3" json:"documentation,omitempty"`
	Relationships          []*Relationship        `protobuf:"bytes,4,rep,name=relationships,proto3" json:"relationships,omitempty"`
	Kind                   SymbolInformation_Kind `protobuf:"varint,5,opt,name=kind,proto3,enum=codeintel.scip.v1.SymbolInformation_Kind" json:"kind,omitempty"`
	DisplayName            string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	SignatureDocumentation *Document              `protobuf:"bytes,7,opt,name=signature_documentation,json=signatureDocumentation,proto3" json:"signature_documentation,omitempty"`
	EnclosingSymbol        string                 `protobuf:"bytes,8,opt,name=enclosing_symbol,json=enclosingSymbol,proto3" json:"enclosing_symbol,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SymbolInformation) Reset() {
	*x = SymbolInformation{}
	mi := &file_scip_v1_scip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolInformation) ProtoMessage() {}

func (x *SymbolInformation) ProtoReflect() protoreflect.Message {
	mi := &file_scip_v1_scip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolInformation.ProtoReflect.Descriptor instead.
func (*SymbolInformation) Descriptor() ([]byte, []int) {
	return file_scip_v1_scip_proto_rawDescGZIP(), []int{3}
}

func (x *SymbolInformation) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SymbolInformation) GetDocumentation() []string {
	if x != nil {
		return x.Documentation
	}
	return nil
}

func (x *SymbolInformation) GetRelationships() []*Relationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *SymbolInformation) GetKind() SymbolInformation_Kind {
	if x != nil {
		return x.Kind
	}
	return SymbolInformation_KIND_UNSPECIFIED
}

func (x *SymbolInformation) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SymbolInformation) GetSignatureDocumentation() *Document {
	if x != nil {
		return x.SignatureDocumentation
	}
	return nil
}

func (x *SymbolInformation) GetEnclosingSymbol() string {
	if x != nil {
		return x.EnclosingSymbol
	}
	return ""
}

type Relationship struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Symbol           string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	IsReference      bool                   `protobuf:"varint,2,opt,name=is_reference,json=isReference,proto3" json:"is_reference,omitempty"`
	IsImplementation bool                   `protobuf:"varint,3,opt,name=is_implementation,json=isImplementation,proto3" json:"is_implementation,omitempty"`
	IsTypeDefinition bool                   `protobuf:"varint,4,opt,name=is_type_definition,json=isTypeDefinition,proto3" json:"is_type_definition,omitempty"`
	IsDefinition     bool                   `protobuf:"varint,5,opt,name=is_definition,json=isDefinition,proto3" json:"is_definition,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_scip_v1_scip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_scip_v1_scip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_scip_v1_scip_proto_rawDescGZIP(), []int{4}
}

func (x *Relationship) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Relationship) GetIsReference() bool {
	if x != nil {
		return x.IsReference
	}
	return false
}

func (x *Relationship) GetIsImplementation() bool {
	if x != nil {
		return x.IsImplementation
	}
	return false
}

func (x *Relationship) GetIsTypeDefinition() bool {
	if x != nil {
		return x.IsTypeDefinition
	}
	return false
}

func (x *Relationship) GetIsDefinition() bool {
	if x != nil {
		return x.IsDefinition
	}
	return false
}

var File_scip_v1_scip_proto protoreflect.FileDescriptor

const file_scip_v1_scip_proto_rawDesc = "" +
	"\n" +
	"\x12scip/v1/scip.proto\x12\x11codeintel.scip.v1\"\x93\x01\n" +
	"\x05Index\x129\n" +
	"\tdocuments\x18\x02 \x03(\v2\x1b.codeintel.scip.v1.DocumentR\tdocuments\x12O\n" +
	"\x10external_symbols\x18\x03 \x03(\v2$.codeintel.scip.v1.SymbolInformationR\x0fexternalSymbols\"\xb2\x02\n" +
	"\bDocument\x12#\n" +
	"\rrelative_path\x18\x01 \x01(\tR\frelativePath\x12?\n" +
	"\voccurrences\x18\x02 \x03(\v2\x1d.codeintel.scip.v1.OccurrenceR\voccurrences\x12>\n" +
	"\asymbols\x18\x03 \x03(\v2$.codeintel.scip.v1.SymbolInformationR\asymbols\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12P\n" +
	"\x11position_encoding\x18\x06 \x01(\x0e2#.codeintel.scip.v1.PositionEncodingR\x10positionEncoding\"\xfd\x01\n" +
	"\n" +
	"Occurrence\x12\x14\n" +
	"\x05range\x18\x01 \x03(\x05R\x05range\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12!\n" +
	"\fsymbol_roles\x18\x03 \x01(\x05R\vsymbolRoles\x125\n" +
	"\x16override_documentation\x18\x04 \x03(\tR\x15overrideDocumentation\x12>\n" +
	"\vsyntax_kind\x18\x05 \x01(\x0e2\x1d.codeintel.scip.v1.SyntaxKindR\n" +
	"syntaxKind\x12'\n" +
	"\x0fenclosing_range\x18\a \x03(\x05R\x0eenclosingRange\"\x9d\r\n" +
	"\x11SymbolInformation\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12$\n" +
	"\rdocumentation\x18\x03 \x03(\tR\rdocumentation\x12E\n" +
	"\rrelationships\x18\x04 \x03(\v2\x1f.codeintel.scip.v1.RelationshipR\rrelationships\x12=\n" +
	"\x04kind\x18\x05 \x01(\x0e2).codeintel.scip.v1.SymbolInformation.KindR\x04kind\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\x12T\n" +
	"\x17signature_documentation\x18\a \x01(\v2\x1b.codeintel.scip.v1.DocumentR\x16signatureDocumentation\x12)\n" +
	"\x10enclosing_symbol\x18\b \x01(\tR\x0fenclosingSymbol\"\x9f\n" +
	"\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ARRAY\x10\x01\x12\r\n" +
	"\tASSERTION\x10\x02\x12\x13\n" +
	"\x0fASSOCIATED_TYPE\x10\x03\x12\r\n" +
	"\tATTRIBUTE\x10\x04\x12\t\n" +
	"\x05AXIOM\x10\x05\x12\v\n" +
	"\aBOOLEAN\x10\x06\x12\t\n" +
	"\x05CLASS\x10\a\x12\f\n" +
	"\bCONSTANT\x10\b\x12\x0f\n" +
	"\vCONSTRUCTOR\x10\t\x12\x0f\n" +
	"\vDATA_FAMILY\x10\n" +
	"\x12\b\n" +
	"\x04ENUM\x10\v\x12\x0f\n" +
	"\vENUM_MEMBER\x10\f\x12\t\n" +
	"\x05EVENT\x10\r\x12\b\n" +
	"\x04FACT\x10\x0e\x12\t\n" +
	"\x05FIELD\x10\x0f\x12\b\n" +
	"\x04FILE\x10\x10\x12\f\n" +
	"\bFUNCTION\x10\x11\x12\n" +
	"\n" +
	"\x06GETTER\x10\x12\x12\v\n" +
	"\aGRAMMAR\x10\x13\x12\f\n" +
	"\bINSTANCE\x10\x14\x12\r\n" +
	"\tINTERFACE\x10\x15\x12\a\n" +
	"\x03KEY\x10\x16\x12\b\n" +
	"\x04LANG\x10\x17\x12\t\n" +
	"\x05LEMMA\x10\x18\x12\t\n" +
	"\x05MACRO\x10\x19\x12\n" +
	"\n" +
	"\x06METHOD\x10\x1a\x12\x13\n" +
	"\x0fMETHOD_RECEIVER\x10\x1b\x12\v\n" +
	"\aMESSAGE\x10\x1c\x12\n" +
	"\n" +
	"\x06MODULE\x10\x1d\x12\r\n" +
	"\tNAMESPACE\x10\x1e\x12\r\n" +
	"\tNULL_KIND\x10\x1f\x12\n" +
	"\n" +
	"\x06NUMBER\x10 \x12\n" +
	"\n" +
	"\x06OBJECT\x10!\x12\f\n" +
	"\bOPERATOR\x10\"\x12\v\n" +
	"\aPACKAGE\x10#\x12\x12\n" +
	"\x0ePACKAGE_OBJECT\x10$\x12\r\n" +
	"\tPARAMETER\x10%\x12\x13\n" +
	"\x0fPARAMETER_LABEL\x10&\x12\v\n" +
	"\aPATTERN\x10'\x12\r\n" +
	"\tPREDICATE\x10(\x12\f\n" +
	"\bPROPERTY\x10)\x12\f\n" +
	"\bPROTOCOL\x10*\x12\x0f\n" +
	"\vQUASIQUOTER\x10+\x12\x12\n" +
	"\x0eSELF_PARAMETER\x10,\x12\n" +
	"\n" +
	"\x06SETTER\x10-\x12\r\n" +
	"\tSIGNATURE\x10.\x12\r\n" +
	"\tSUBSCRIPT\x10/\x12\n" +
	"\n" +
	"\x06STRING\x100\x12\n" +
	"\n" +
	"\x06STRUCT\x101\x12\n" +
	"\n" +
	"\x06TACTIC\x102\x12\v\n" +
	"\aTHEOREM\x103\x12\x12\n" +
	"\x0eTHIS_PARAMETER\x104\x12\t\n" +
	"\x05TRAIT\x105\x12\b\n" +
	"\x04TYPE\x106\x12\x0e\n" +
	"\n" +
	"TYPE_ALIAS\x107\x12\x0e\n" +
	"\n" +
	"TYPE_CLASS\x108\x12\x0f\n" +
	"\vTYPE_FAMILY\x109\x12\x12\n" +
	"\x0eTYPE_PARAMETER\x10:\x12\t\n" +
	"\x05UNION\x10;\x12\t\n" +
	"\x05VALUE\x10<\x12\f\n" +
	"\bVARIABLE\x10=\x12\f\n" +
	"\bCONTRACT\x10>\x12\t\n" +
	"\x05ERROR\x10?\x12\v\n" +
	"\aLIBRARY\x10@\x12\f\n" +
	"\bMODIFIER\x10A\x12\x13\n" +
	"\x0fABSTRACT_METHOD\x10B\x12\x18\n" +
	"\x14METHOD_SPECIFICATION\x10C\x12\x13\n" +
	"\x0fPROTOCOL_METHOD\x10D\x12\x17\n" +
	"\x13PURE_VIRTUAL_METHOD\x10E\x12\x10\n" +
	"\fTRAIT_METHOD\x10F\x12\x15\n" +
	"\x11TYPE_CLASS_METHOD\x10G\x12\f\n" +
	"\bACCESSOR\x10H\x12\f\n" +
	"\bDELEGATE\x10I\x12\x10\n" +
	"\fMETHOD_ALIAS\x10J\x12\x13\n" +
	"\x0fSINGLETON_CLASS\x10K\x12\x14\n" +
	"\x10SINGLETON_METHOD\x10L\x12\x16\n" +
	"\x12STATIC_DATA_MEMBER\x10M\x12\x10\n" +
	"\fSTATIC_EVENT\x10N\x12\x10\n" +
	"\fSTATIC_FIELD\x10O\x12\x11\n" +
	"\rSTATIC_METHOD\x10P\x12\x13\n" +
	"\x0fSTATIC_PROPERTY\x10Q\x12\x13\n" +
	"\x0fSTATIC_VARIABLE\x10R\x12\r\n" +
	"\tEXTENSION\x10T\x12\t\n" +
	"\x05MIXIN\x10U\x12\v\n" +
	"\aCONCEPT\x10V\"\xc9\x01\n" +
	"\fRelationship\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12!\n" +
	"\fis_reference\x18\x02 \x01(\bR\visReference\x12+\n" +
	"\x11is_implementation\x18\x03 \x01(\bR\x10isImplementation\x12,\n" +
	"\x12is_type_definition\x18\x04 \x01(\bR\x10isTypeDefinition\x12#\n" +
	"\ris_definition\x18\x05 \x01(\bR\fisDefinition*\xb8\x01\n" +
	"\x10PositionEncoding\x12!\n" +
	"\x1dPOSITION_ENCODING_UNSPECIFIED\x10\x00\x12)\n" +
	"%UTF8_CODE_UNIT_OFFSET_FROM_LINE_START\x10\x01\x12*\n" +
	"&UTF16_CODE_UNIT_OFFSET_FROM_LINE_START\x10\x02\x12*\n" +
	"&UTF32_CODE_UNIT_OFFSET_FROM_LINE_START\x10\x03*\x99\x01\n" +
	"\n" +
	"SymbolRole\x12\x1b\n" +
	"\x17SYMBOL_ROLE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"DEFINITION\x10\x01\x12\n" +
	"\n" +
	"\x06IMPORT\x10\x02\x12\x10\n" +
	"\fWRITE_ACCESS\x10\x04\x12\x0f\n" +
	"\vREAD_ACCESS\x10\b\x12\r\n" +
	"\tGENERATED\x10\x10\x12\b\n" +
	"\x04TEST\x10 \x12\x16\n" +
	"\x12FORWARD_DEFINITION\x10@*\xda\x06\n" +
	"\n" +
	"SyntaxKind\x12\x1b\n" +
	"\x17SYNTAX_KIND_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCOMMENT\x10\x01\x12\x19\n" +
	"\x15PUNCTUATION_DELIMITER\x10\x02\x12\x17\n" +
	"\x13PUNCTUATION_BRACKET\x10\x03\x12\v\n" +
	"\aKEYWORD\x10\x04\x12\x17\n" +
	"\x13IDENTIFIER_OPERATOR\x10\x05\x12\x0e\n" +
	"\n" +
	"IDENTIFIER\x10\x06\x12\x16\n" +
	"\x12IDENTIFIER_BUILTIN\x10\a\x12\x13\n" +
	"\x0fIDENTIFIER_NULL\x10\b\x12\x17\n" +
	"\x13IDENTIFIER_CONSTANT\x10\t\x12\x1d\n" +
	"\x19IDENTIFIER_MUTABLE_GLOBAL\x10\n" +
	"\x12\x18\n" +
	"\x14IDENTIFIER_PARAMETER\x10\v\x12\x14\n" +
	"\x10IDENTIFIER_LOCAL\x10\f\x12\x17\n" +
	"\x13IDENTIFIER_SHADOWED\x10\r\x12\x18\n" +
	"\x14IDENTIFIER_NAMESPACE\x10\x0e\x12\x17\n" +
	"\x13IDENTIFIER_FUNCTION\x10\x0f\x12\"\n" +
	"\x1eIDENTIFIER_FUNCTION_DEFINITION\x10\x10\x12\x14\n" +
	"\x10IDENTIFIER_MACRO\x10\x11\x12\x1f\n" +
	"\x1bIDENTIFIER_MACRO_DEFINITION\x10\x12\x12\x13\n" +
	"\x0fIDENTIFIER_TYPE\x10\x13\x12\x1b\n" +
	"\x17IDENTIFIER_BUILTIN_TYPE\x10\x14\x12\x18\n" +
	"\x14IDENTIFIER_ATTRIBUTE\x10\x15\x12\x10\n" +
	"\fREGEX_ESCAPE\x10\x16\x12\x12\n" +
	"\x0eREGEX_REPEATED\x10\x17\x12\x12\n" +
	"\x0eREGEX_WILDCARD\x10\x18\x12\x13\n" +
	"\x0fREGEX_DELIMITER\x10\x19\x12\x0e\n" +
	"\n" +
	"REGEX_JOIN\x10\x1a\x12\x12\n" +
	"\x0eSTRING_LITERAL\x10\x1b\x12\x19\n" +
	"\x15STRING_LITERAL_ESCAPE\x10\x1c\x12\x1a\n" +
	"\x16STRING_LITERAL_SPECIAL\x10\x1d\x12\x16\n" +
	"\x12STRING_LITERAL_KEY\x10\x1e\x12\x15\n" +
	"\x11CHARACTER_LITERAL\x10\x1f\x12\x13\n" +
	"\x0fNUMERIC_LITERAL\x10 \x12\x13\n" +
	"\x0fBOOLEAN_LITERAL\x10!\x12\a\n" +
	"\x03TAG\x10\"\x12\x11\n" +
	"\rTAG_ATTRIBUTE\x10#\x12\x11\n" +
	"\rTAG_DELIMITER\x10$B Z\x1ecodeintel/proto/scip/v1;scippbb\x06proto3"

var (
	file_scip_v1_scip_proto_rawDescOnce sync.Once
	file_scip_v1_scip_proto_rawDescData []byte
)

func file_scip_v1_scip_proto_rawDescGZIP() []byte {
	file_scip_v1_scip_proto_rawDescOnce.Do(func() {
		file_scip_v1_scip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scip_v1_scip_proto_rawDesc), len(file_scip_v1_scip_proto_rawDesc)))
	})
	return file_scip_v1_scip_proto_rawDescData
}

var file_scip_v1_scip_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_scip_v1_scip_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_scip_v1_scip_proto_goTypes = []any{
	(PositionEncoding)(0),       // 0: codeintel.scip.v1.PositionEncoding
	(SymbolRole)(0),             // 1: codeintel.scip.v1.SymbolRole
	(SyntaxKind)(0),             // 2: codeintel.scip.v1.SyntaxKind
	(SymbolInformation_Kind)(0), // 3: codeintel.scip.v1.SymbolInformation.Kind
	(*Index)(nil),               // 4: codeintel.scip.v1.Index
	(*Document)(nil),            // 5: codeintel.scip.v1.Document
	(*Occurrence)(nil),          // 6: codeintel.scip.v1.Occurrence
	(*SymbolInformation)(nil),   // 7: codeintel.scip.v1.SymbolInformation
	(*Relationship)(nil),        // 8: codeintel.scip.v1.Relationship
}
var file_scip_v1_scip_proto_depIdxs = []int32{
	5, // 0: codeintel.scip.v1.Index.documents:type_name -> codeintel.scip.v1.Document
	7, // 1: codeintel.scip.v1.Index.external_symbols:type_name -> codeintel.scip.v1.SymbolInformation
	6, // 2: codeintel.scip.v1.Document.occurrences:type_name -> codeintel.scip.v1.Occurrence
	7, // 3: codeintel.scip.v1.Document.symbols:type_name -> codeintel.scip.v1.SymbolInformation
	0, // 4: codeintel.scip.v1.Document.position_encoding:type_name -> codeintel.scip.v1.PositionEncoding
	2, // 5: codeintel.scip.v1.Occurrence.syntax_kind:type_name -> codeintel.scip.v1.SyntaxKind
	8, // 6: codeintel.scip.v1.SymbolInformation.relationships:type_name -> codeintel.scip.v1.Relationship
	3, // 7: codeintel.scip.v1.SymbolInformation.kind:type_name -> codeintel.scip.v1.SymbolInformation.Kind
	5, // 8: codeintel.scip.v1.SymbolInformation.signature_documentation:type_name -> codeintel.scip.v1.Document
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_scip_v1_scip_proto_init() }
func file_scip_v1_scip_proto_init() {
	if File_scip_v1_scip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scip_v1_scip_proto_rawDesc), len(file_scip_v1_scip_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scip_v1_scip_proto_goTypes,
		DependencyIndexes: file_scip_v1_scip_proto_depIdxs,
		EnumInfos:         file_scip_v1_scip_proto_enumTypes,
		MessageInfos:      file_scip_v1_scip_proto_msgTypes,
	}.Build()
	File_scip_v1_scip_proto = out.File
	file_scip_v1_scip_proto_goTypes = nil
	file_scip_v1_scip_proto_depIdxs = nil
}
